// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.com.gestionreservation2.web.grpc.stubs;

public interface GetReservationByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  ma.projet.com.gestionreservation2.web.grpc.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  ma.projet.com.gestionreservation2.web.grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
