// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.com.gestionreservation2.web.grpc.stubs;

public interface UpdateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.Reservation reservation = 2;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 2;</code>
   * @return The reservation.
   */
  ma.projet.com.gestionreservation2.web.grpc.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 2;</code>
   */
  ma.projet.com.gestionreservation2.web.grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
